export const agents = [
  {
    id: "chat-agent",
    name: "AI Chat",
    type: "chat",
    description: "General AI assistant",
    icon: "💬",
  },
  {
    id: "image-agent",
    name: "Image Generator",
    type: "image",
    description: "Generate AI images",
    icon: "🎨",
  },
  {
    id: "coding-agent",
    name: "Code Assistant",
    type: "chat",
    description: "Write & fix code",
    icon: "💻",
  },
  {
    id: "seo-agent",
    name: "SEO Writer",
    type: "chat",
    description: "SEO blogs & keywords",
    icon: "📈",
  },
  {
    id: "resume-agent",
    name: "Resume Builder",
    type: "chat",
    description: "Professional resumes",
    icon: "📄",
  },
  {
    id: "email-agent",
    name: "Email Writer",
    type: "chat",
    description: "Professional emails",
    icon: "📧",
  },
  {
    id: "research-agent",
    name: "Research Agent",
    type: "chat",
    description: "Research & summaries",
    icon: "🔍",
  },
  {
    id: "data-agent",
    name: "Data Analyst",
    type: "chat",
    description: "Analyze data",
    icon: "📊",
  },
];